### ISSUE TITLE
slf4j classes in liquibase-teradata jar

### ISSUE THREAD

**Issue by zehndton** [liquibase/liquibase-teradata#112]
Hi guys,
when updating from 4.24.0 to 4.25.0 there is an issue with SLF4J.

It's not possible to exclude the slf4j-simple dependency:
```
            <dependency>
                <groupId>org.liquibase.ext</groupId>
                <artifactId>liquibase-teradata</artifactId>
                <version>2.55.0</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-simple</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```
This causes that you can not bind another SLF4J provider since org.slf4j.simple.SimpleServiceProvider / slf4j-simple is on the class path.
-> https://www.slf4j.org/codes.html#multiple_bindings

Probably the jar build changed and the slf4j package are now part of the liquibase-teradata artefact.
Version 2.25.0:
![image](https://github.com/liquibase/liquibase-teradata/assets/2572343/9fccf5a1-b3cd-4f62-b1de-99cb334b60cf)

Version 2.24.0:
![image](https://github.com/liquibase/liquibase-teradata/assets/2572343/d8e86ead-d27a-4add-bdfe-1314e8a27ef2)

**Comment by filipelautert** [comment]
Hi - this should be fixed on 4.27.0 that will be released later this week. 
If the problem persists please reopen the ticket!
