### ISSUE TITLE
Boolean type error

### ISSUE THREAD

**Issue by cmmarslender** [liquibase/liquibase-teradata#32]
Hello,

I'm getting the following error: 

```
Unexpected error running Liquibase: [Teradata Database] [TeraJDBC 17.00.00.03] [Error 3706] [SQLState 42000] Syntax error: Data Type "BOOLEAN" does not match a Defined Type name. [Failed SQL: (3706) CREATE TABLE DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BOOLEAN NOT NULL, LOCKGRANTED datetime, LOCKEDBY VARCHAR(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID))]
```

I'm using the latest liquibase docker image + adding this plugin and the jdbc connector for teradata to the /liquibase/lib directory, then trying to run a test migration, and its stopping at the point of creating the migration tables with that error..

Let me know if any further information would be useful for debugging.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-990) by [Unito](https://www.unito.io/learn-more)

**Comment by Yuriy-Leonov** [comment]
@cmmarslender Hi, sorry for disturbing you. Was this issue resolved somehow?
Because I can't get access to assigned Jira Bug, but I've faced with exactly same exception.

**Comment by cmmarslender** [comment]
@Yuriy-Leonov In my case, the plugin jar for terradata existed but was empty for some reason, so I re-downloaded and it worked.
